#pragma once

#include <NativeGameplayTags.h>

GAMEBASEFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN( GBFTag_InitState_Spawned );
GAMEBASEFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN( GBFTag_InitState_DataAvailable );
GAMEBASEFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN( GBFTag_InitState_DataInitialized );
GAMEBASEFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN( GBFTag_InitState_GameplayReady );