title: Game Base Framework for Unreal Engine
description: An Unreal Engine plugin to help you kickstart a new project or expand an existing one
theme: just-the-docs

url: https://theemidee.github.io/UEGameBaseFramework/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
